<footer id="footer" class="footer">

    <div class="container">
      <div class="copyright text-center ">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">Raihan Fauzan</strong> <span>All Rights Reserved<br></span></p>
      </div>
      <div class="social-links d-flex justify-content-center">
        <a href="https://www.instagram.com/amar_0218?igsh=cmFvNDk4aG9zazE=" target="_blank"><i class="bi bi-instagram"></i></a>
        <a href="https://www.linkedin.com/in/raihan-fauzan-7b033732b/" target="_blank"><i class="bi bi-linkedin"></i></a>
        <a href="https://github.com/rehanFauzan/" target="_blank"><i class="bi bi-github"></i></a>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer>
